"""
Base class for all musical agents in the Agentic Symphony system.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any
from core.context import MusicalContext


class MusicalAgent(ABC):
    """
    Abstract base class for musical agents.

    Each agent has a specific role (harmonic, melodic, rhythmic, textural)
    and contributes to the composition by reading the shared context,
    making decisions, and generating MIDI events.
    """

    def __init__(self, role: str, objectives: Dict[str, Any] = None):
        """
        Initialize the musical agent.

        Args:
            role: The agent's role (e.g., "harmonic", "melodic")
            objectives: Dictionary of agent-specific objectives and parameters
        """
        self.role = role
        self.objectives = objectives or {}
        self.memory = []  # Agent's own history of decisions
        self.max_memory = 32  # Keep last 32 decisions

    @abstractmethod
    def listen(self, context: MusicalContext) -> Dict[str, Any]:
        """
        Analyze the current musical context and extract relevant features.

        This is where the agent "listens" to what's happening in the composition
        and gathers information needed for decision-making.

        Args:
            context: The shared musical context

        Returns:
            Dictionary of analyzed features relevant to this agent
        """
        pass

    @abstractmethod
    def decide(self, analysis: Dict[str, Any], context: MusicalContext) -> Dict[str, Any]:
        """
        Make a musical decision based on the analysis and agent's objectives.

        This is the core decision-making logic where the agent determines
        what musical action to take.

        Args:
            analysis: The analyzed features from listen()
            context: The shared musical context

        Returns:
            Dictionary describing the decision made
        """
        pass

    @abstractmethod
    def act(self, decision: Dict[str, Any], context: MusicalContext) -> List[Dict[str, Any]]:
        """
        Generate MIDI events based on the decision.

        This converts the agent's decision into concrete MIDI events
        (note on/off, control changes, etc.) and updates the context.

        Args:
            decision: The decision from decide()
            context: The shared musical context (will be modified)

        Returns:
            List of MIDI event dictionaries with keys:
                - type: "note_on", "note_off", "control_change", etc.
                - note: MIDI note number (for note events)
                - velocity: MIDI velocity (0-127)
                - time: Time in beats from now
                - channel: MIDI channel (0-15)
                - duration: Note duration in beats (optional)
        """
        pass

    def step(self, context: MusicalContext) -> List[Dict[str, Any]]:
        """
        Execute one full step of the agent's process.

        This is the main method called by the conductor to have the agent
        contribute to the composition.

        Args:
            context: The shared musical context

        Returns:
            List of MIDI events generated by this agent
        """
        # 1. Listen to the current state
        analysis = self.listen(context)

        # 2. Decide what to do
        decision = self.decide(analysis, context)

        # 3. Act on the decision (generates MIDI and updates context)
        events = self.act(decision, context)

        # 4. Remember this decision
        self._add_to_memory(decision)

        return events

    def _add_to_memory(self, decision: Dict[str, Any]):
        """
        Add a decision to the agent's memory.

        Args:
            decision: The decision to remember
        """
        self.memory.append(decision)
        if len(self.memory) > self.max_memory:
            self.memory = self.memory[-self.max_memory:]

    def get_recent_memory(self, n: int = 8) -> List[Dict[str, Any]]:
        """
        Get the most recent n decisions from memory.

        Args:
            n: Number of recent decisions to retrieve

        Returns:
            List of recent decisions
        """
        return self.memory[-n:] if self.memory else []

    def reset(self):
        """Reset the agent's internal state."""
        self.memory = []

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(role='{self.role}')"
